### PR TITLE
Lecture Outlier: Updated Lecture 

### PR DESCRIPTION
**Pull request by melsigl**
Updated lecture slides for a well rounded lecture.

### CODE REVIEW

**Review by dominik-probst — APPROVED** [review]
I have no major points to note in this case. The only two minor things I would like to note are:

1. On slide 17/18 and on slide 23/24, the header numbering ( "(2)" ) differs from the rest (e.g. slide 26-28 "I" - "III").
2. On slide 18, 21, 22, 26 there are numbered formulas. 

I was also a bit surprised about the numbering of the tex files. Here the number 5 seems to be missing. Is there a reason for this?

Since I didn't know if you would be able to fix it by Friday, I approve the commit despite my two minor comments. If there is not enough time to fix it, this is something for next semester.

**Comment by dominik-probst** [comment]
I just noticed a bigger mistake while I am preparing the final set of slides: The numbering of the lecture does not match the rest of our numbering (7th instead of 9th). 

If you don't have time to fix it yourself, I can do it for you. But we should definitely fix this before uploading.

**Review by dominik-probst — CHANGES_REQUESTED** [review]
I just noticed a bigger mistake while I am preparing the final set of slides: The numbering of the lecture does not match the rest of our numbering (7th instead of 9th).

If you don't have time to fix it yourself, I can do it for you. But we should definitely fix this before uploading.

**Comment by melsigl** [comment]
I am at a loss at what you mean with the numbering. Let me clarify:
1. Numbering of `tex`-files: I did not change the file `5-summary.tex` as it seemed perfectly fine. This file is already on dev (and main branch for that matter) and is therefore not included in this PR as only changed files appear.
2. Numbering of lectures: This took me a little while without context of what you meant. The title of the lecture is inconsistent with the actual numbering and we have the number of lecture hardcoded. This is easily fixable.

Thanks for pointing out the numbering of some equations. 

Will find time to squeeze in these changes later on.

**Comment by melsigl** [comment]
Done.

Frame title numbering on slide 18 is intentional, as it already got roman numbering in the first part of the title. It would look weird to have two roman numberings in a title simultaneously.

**Review by dominik-probst — APPROVED** [review]
You are, of course, absolutely correct about file number 5. I misinterpreted the list of files in the review area of GitHub as a complete list of files rather than a selective list of changed files. 

You also interpreted the numbering of the lecture correctly.  If something in my reviews is not understandable, you are welcome to ask.

**Pull request merged**
